name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test_churn.py
      id: test_churn-py
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 25
        setup-command: pip install pytest
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_CHURN-PY_RESULTS: "${{steps.test_churn-py.outputs.result}}"
      with:
        runners: test_churn-py
